dsciitpatna/SAAR-Android-Client

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/chore.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> Add pull request and issue template

- app/src/main/java/com/example/saar/AboutUsFragment.java
- app/src/main/java/com/example/saar/HomeFragment.java
- app/src/main/java/com/example/saar/MainActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/app_bar_main.xml
- app/src/main/res/layout/content_main.xml
- app/src/main/res/layout/fragment_about_us.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/values/strings.xml
Fixes #13 
Changes: Added Fragments
> fix: Added HomeFragment and AboutUsFragment

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/chore.md
- .github/ISSUE_TEMPLATE/feature_request.md
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
> Update pull request and issue templates

- .circleci/config.yml
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
> Circle ci file added

- app/build.gradle
- app/src/main/java/com/example/saar/Constant.java
- app/src/main/java/com/example/saar/DonateFragment.java
- app/src/main/java/com/example/saar/MainActivity.java
- app/src/main/res/layout/fragment_donate.xml
- app/src/main/res/values/strings.xml
> feat: Added Donate Page

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/saar/Constant.java
- app/src/main/java/com/example/saar/Event.java
- app/src/main/java/com/example/saar/EventAdapter.java
- app/src/main/java/com/example/saar/GetDataService.java
- app/src/main/java/com/example/saar/MainActivity.java
- app/src/main/java/com/example/saar/RetrofitClientInstance.java
- app/src/main/java/com/example/saar/TimelineFragment.java
- app/src/main/res/layout/event_list_row.xml
- app/src/main/res/layout/fragment_timeline.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Fixes #32 
Changes: Added Timeline Fragment
It has TimelineView .
It gets data from server in json format using Retrofit2.
> feat: Added Timeline Page

- app/src/main/java/com/example/saar/ContactFragment.java
- app/src/main/java/com/example/saar/MainActivity.java
- app/src/main/res/drawable/ic_place_black_24dp.xml
- app/src/main/res/layout/fragment_contact.xml
- app/src/main/res/menu/activity_main_drawer.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Fixes #35 
Changes: Added ContactUs Page.
Added Map Support.
> feat: Added Contact Us Page and Map Support

- app/src/main/java/com/example/saar/Gallery.java
- app/src/main/java/com/example/saar/GalleryAdapter.java
- app/src/main/java/com/example/saar/GalleryFragment.java
- app/src/main/java/com/example/saar/GetDataService.java
- app/src/main/java/com/example/saar/MainActivity.java
- app/src/main/res/layout/fragment_gallery.xml
- app/src/main/res/layout/gallery_list_row.xml
- app/src/main/res/values/strings.xml
Fixes #42 
Changes: 
Added Gallery Page which takes data from server.
> feat: Added Gallery Page

- app/src/main/res/drawable/round_button.xml
- app/src/main/res/layout/fragment_donate.xml
> Changed rectangular button to circular button in Donate Fragment.

- app/src/main/res/drawable/round_button.xml
- app/src/main/res/layout/fragment_donate.xml
Reverts dsciitpatna/SAAR-Android-Client#46
> Revert "Changed rectangular button to circular button in Donate Fragment."

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/saar/About/AboutUsFragment.java
- app/src/main/java/com/example/saar/Contact/ContactFragment.java
- app/src/main/java/com/example/saar/Donate/DonateFragment.java
- app/src/main/java/com/example/saar/Gallery/Gallery.java
- app/src/main/java/com/example/saar/Gallery/GalleryAdapter.java
- app/src/main/java/com/example/saar/Gallery/GalleryFragment.java
- app/src/main/java/com/example/saar/Home/HomeFragment.java
- app/src/main/java/com/example/saar/Login_SignUp/LoginFragment.java
- app/src/main/java/com/example/saar/Login_SignUp/LoginSignupActivity.java
- app/src/main/java/com/example/saar/Login_SignUp/SignUpFragment.java
- app/src/main/java/com/example/saar/MainActivity.java
- app/src/main/java/com/example/saar/Retrofit/GetDataService.java
- app/src/main/java/com/example/saar/Retrofit/RetrofitClientInstance.java
- app/src/main/java/com/example/saar/Share/ShareFragment.java
- app/src/main/java/com/example/saar/Team/TeamFragment.java
- app/src/main/java/com/example/saar/Timeline_Events/Event.java
- app/src/main/java/com/example/saar/Timeline_Events/EventAdapter.java
- app/src/main/java/com/example/saar/Timeline_Events/EventDetails.java
- app/src/main/java/com/example/saar/Timeline_Events/TimelineFragment.java
- app/src/main/res/layout/activity_login_signup.xml
- app/src/main/res/layout/fragment_about_us.xml
- app/src/main/res/layout/fragment_contact.xml
- app/src/main/res/layout/fragment_donate.xml
- app/src/main/res/layout/fragment_gallery.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_sign_up.xml
- app/src/main/res/layout/fragment_timeline.xml
Fixes #44 
Changes: Refactored full code.
> fix: Refactored Code

- app/src/main/res/layout/app_bar_main.xml
- app/src/main/res/values/styles.xml
Fixes #40 
Changes:   android:background="?attr/colorPrimaryDark"
> Changed the color to colorPrimaryDark

- app/src/main/res/layout/fragment_donate.xml
Fixes #34 
Changes: Changed background of Donate Button.
> Updated background of Donate button

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/saar/Login_SignUp/SignUpFragment.java
- app/src/main/res/layout/fragment_sign_up.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Fixes #53
Changes: Sign up page added
> Added sign up page

- app/src/main/java/com/example/saar/Team/TeamFragment.java
Fixes #31 
Changes: Added Facebook intent on each team member's ImageView and Toast for those whose Profile doesn't exist in TeamFragment.Java.
> Updated the TeamFragment.Java.

- app/src/main/res/layout/fragment_donate.xml
Fixes #55 
Changes: Changed textSize from Big to medium in Donate_Button.
> Updated fragment_Donate.xml.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/saar/Notifications/FcmMessagingService.java
- app/src/main/java/com/example/saar/Notifications/MySingleton.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Fixes #45 
Changes: [Add here what changes were made in this issue and if possible provide links.]
> feat: Image notification implemented

- app/src/main/java/com/example/saar/MainActivity.java
- app/src/main/java/com/example/saar/Notifications/FcmMessagingService.java
- app/src/main/res/values/strings.xml
Fixes #62 
Changes: 
Admin can now send message to all the devices by simply sending the notification to  "topics/alumnus"
> feat: Topic messaging implemented

- app/src/main/java/com/example/saar/Notifications/FcmMessagingService.java
Integrated the feature to send a notification in topics without an image.
> feat:Admin is now able to send only text notification.

- app/google-services.json
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
> google-service.json added

- .gitignore
> Git ignore file modified

- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/layout/fragment_about_us.xml
- app/src/main/res/layout/fragment_contact.xml
- app/src/main/res/layout/fragment_gallery.xml
- app/src/main/res/layout/fragment_login.xml
- app/src/main/res/layout/fragment_sign_up.xml
- app/src/main/res/layout/fragment_team.xml
- app/src/main/res/layout/fragment_timeline.xml
- app/src/main/res/values/colors.xml
> Updated color.xml

- app/src/main/java/com/example/saar/MainActivity.java
- app/src/main/res/layout/fragment_about_us.xml
Fixes #70
Changes: On clicking the back button home fragment opens up 
> Implement Back button press

- app/src/main/res/layout/fragment_team.xml
Fixes #78 
Changes:
The committees were re positioned
> fix: Reposition in team fragment

- app/src/main/java/com/example/saar/Timeline_Events/EventAdapter.java
Fixes #80 
Changes: Removed keyword "final".
used getAdapterposition().
> fix: Minor fix in EventAdapter

- app/build.gradle
- app/src/main/java/com/example/saar/Gallery/GalleryAdapter.java
- app/src/main/java/com/example/saar/Timeline_Events/EventDetails.java
> bug: fixed errors in manifest file
